import type { Express } from "express";
import passport from "passport";
import bcrypt from "bcryptjs";
import { authStorage } from "./storage";
import { isAuthenticated } from "./replitAuth";

const BCRYPT_ROUNDS = 12;

// Register auth-specific routes
export function registerAuthRoutes(app: Express): void {
  // POST /api/login — authenticate with email + password
  app.post("/api/login", (req, res, next) => {
    passport.authenticate("local", (err: any, user: any, info: any) => {
      if (err) return next(err);
      if (!user) {
        return res.status(401).json({ message: info?.message ?? "Invalid credentials" });
      }
      req.logIn(user, (loginErr) => {
        if (loginErr) return next(loginErr);
        return res.json(user.claims);
      });
    })(req, res, next);
  });

  // POST /api/logout — destroy session
  app.post("/api/logout", (req, res, next) => {
    req.logout((err) => {
      if (err) return next(err);
      res.sendStatus(200);
    });
  });

  // GET /api/auth/user — returns claims for the currently authenticated user
  app.get("/api/auth/user", isAuthenticated, (req: any, res) => {
    res.json(req.user.claims);
  });

  // POST /api/register — create a new user account with a hashed password
  app.post("/api/register", async (req: any, res, next) => {
    try {
      const { email, password, firstName, lastName } = req.body;
      if (!email || !password) {
        return res.status(400).json({ message: "email and password are required" });
      }

      // Reject duplicate emails
      const existing = await authStorage.getUserByEmail(email);
      if (existing) {
        return res.status(409).json({ message: "An account with that email already exists" });
      }

      const passwordHash = await bcrypt.hash(password, BCRYPT_ROUNDS);

      // Create the user row (id auto-generated by the DB)
      const newUser = await authStorage.upsertUser({
        email,
        firstName: firstName ?? null,
        lastName: lastName ?? null,
      });

      // Store the password hash in the extra column
      await authStorage.setUserPassword(newUser.id, passwordHash);

      return res.status(201).json({ id: newUser.id, email: newUser.email });
    } catch (err) {
      next(err);
    }
  });
}
