export type BadgeCategory = "getting_started" | "milestones" | "race_highlights" | "hot_streaks" | "season_heroes" | "legends" | "league_laughs" | "tier_achievements";

export interface PredefinedBadge {
  slug: string;
  name: string;
  description: string;
  category: BadgeCategory;
  iconName: string;
  iconColor: string;
  criteria: string;
  threshold?: number;
  sortOrder: number;
}

export const BADGE_CATEGORIES: { value: BadgeCategory; label: string }[] = [
  { value: "getting_started", label: "Getting Started" },
  { value: "milestones", label: "Milestones" },
  { value: "race_highlights", label: "Race Highlights" },
  { value: "hot_streaks", label: "Hot Streaks" },
  { value: "season_heroes", label: "Season Heroes" },
  { value: "tier_achievements", label: "Tier Achievements" },
  { value: "legends", label: "Legends" },
  { value: "league_laughs", label: "League Laughs" },
];

export const PREDEFINED_BADGES: PredefinedBadge[] = [
  // Getting Started (4 badges)
  {
    slug: "first_race",
    name: "First Race Completed",
    description: "Awarded for finishing your first race",
    category: "getting_started",
    iconName: "badge_checkered_flag",
    iconColor: "#22c55e",
    criteria: "first_race",
    threshold: 1,
    sortOrder: 1,
  },
  {
    slug: "season_complete",
    name: "Season Complete",
    description: "Take part in all races in a season",
    category: "getting_started",
    iconName: "badge_calendar_check",
    iconColor: "#3b82f6",
    criteria: "season_complete",
    sortOrder: 2,
  },
  {
    slug: "iron_driver",
    name: "Iron Driver",
    description: "Attend and finish every race in the season",
    category: "getting_started",
    iconName: "badge_iron_shield",
    iconColor: "#71717a",
    criteria: "iron_driver",
    sortOrder: 3,
  },
  {
    slug: "never_quit",
    name: "Never Quit",
    description: "Participate in all races despite finishing P8 or below",
    category: "getting_started",
    iconName: "badge_fist",
    iconColor: "#f97316",
    criteria: "never_quit",
    sortOrder: 4,
  },

  // Milestones (4 badges)
  {
    slug: "first_podium",
    name: "First Podium",
    description: "Finish top 3 for the first time",
    category: "milestones",
    iconName: "badge_podium",
    iconColor: "#eab308",
    criteria: "first_podium",
    threshold: 1,
    sortOrder: 5,
  },
  {
    slug: "first_win",
    name: "First Win",
    description: "Win your first race",
    category: "milestones",
    iconName: "badge_trophy_star",
    iconColor: "#f59e0b",
    criteria: "first_win",
    threshold: 1,
    sortOrder: 6,
  },
  {
    slug: "late_bloomer",
    name: "Late Bloomer",
    description: "Achieve your first podium after 3+ races",
    category: "milestones",
    iconName: "badge_flower",
    iconColor: "#ec4899",
    criteria: "late_bloomer",
    threshold: 3,
    sortOrder: 7,
  },
  {
    slug: "first_promotion",
    name: "First Promotion",
    description: "Earn your first promotion to the next tier",
    category: "milestones",
    iconName: "badge_arrow_up_circle",
    iconColor: "#8b5cf6",
    criteria: "first_promotion",
    sortOrder: 8,
  },
  // Race Highlights (3 badges)
  {
    slug: "pole_position",
    name: "Pole Position",
    description: "Qualify P1",
    category: "race_highlights",
    iconName: "badge_lightning",
    iconColor: "#fbbf24",
    criteria: "pole_position",
    threshold: 1,
    sortOrder: 9,
  },
  {
    slug: "grid_climber",
    name: "Grid Climber",
    description: "Finish 3+ positions higher than your qualifying position",
    category: "race_highlights",
    iconName: "badge_mountain",
    iconColor: "#14b8a6",
    criteria: "grid_climber",
    threshold: 3,
    sortOrder: 10,
  },
  {
    slug: "perfect_weekend",
    name: "Perfect Weekend",
    description: "Qualify P1 and finish P1 in the same race",
    category: "race_highlights",
    iconName: "badge_star_burst",
    iconColor: "#f59e0b",
    criteria: "perfect_weekend",
    sortOrder: 11,
  },

  // Hot Streaks (4 badges)
  {
    slug: "back_to_back",
    name: "Back to Back",
    description: "Win two consecutive races",
    category: "hot_streaks",
    iconName: "badge_double_check",
    iconColor: "#ef4444",
    criteria: "back_to_back",
    threshold: 2,
    sortOrder: 12,
  },
  {
    slug: "podium_run",
    name: "Podium Run",
    description: "Finish on the podium in 3 consecutive races",
    category: "hot_streaks",
    iconName: "badge_fire",
    iconColor: "#f97316",
    criteria: "podium_run",
    threshold: 3,
    sortOrder: 13,
  },
  {
    slug: "top_5_regular",
    name: "Top 5 Regular",
    description: "Finish top 5 in 3 races in a season",
    category: "hot_streaks",
    iconName: "badge_consistency",
    iconColor: "#06b6d4",
    criteria: "top_5_regular",
    threshold: 3,
    sortOrder: 14,
  },
  {
    slug: "quali_specialist",
    name: "Quali Specialist",
    description: "Qualify in the top 3 five times in a season",
    category: "hot_streaks",
    iconName: "badge_stopwatch",
    iconColor: "#8b5cf6",
    criteria: "quali_specialist",
    threshold: 5,
    sortOrder: 15,
  },

  // Season Heroes (10 badges)
  {
    slug: "points_scorer",
    name: "Points Scorer",
    description: "Score 100+ points in a season",
    category: "season_heroes",
    iconName: "badge_hundred",
    iconColor: "#22c55e",
    criteria: "points_scorer",
    threshold: 100,
    sortOrder: 16,
  },
  {
    slug: "best_of_rest",
    name: "Best of the Rest",
    description: "Finish 4th overall in the championship",
    category: "season_heroes",
    iconName: "badge_ribbon",
    iconColor: "#64748b",
    criteria: "best_of_rest",
    sortOrder: 17,
  },
  {
    slug: "mck_champion",
    name: "MCK Champion",
    description: "Finish 1st in the championship",
    category: "season_heroes",
    iconName: "badge_crown",
    iconColor: "#fbbf24",
    criteria: "mck_champion",
    sortOrder: 18,
  },
  {
    slug: "runner_up",
    name: "Runner-Up",
    description: "Finish 2nd overall",
    category: "season_heroes",
    iconName: "badge_medal_silver",
    iconColor: "#94a3b8",
    criteria: "runner_up",
    sortOrder: 19,
  },
  {
    slug: "third_overall",
    name: "Third Overall",
    description: "Finish 3rd overall",
    category: "season_heroes",
    iconName: "badge_medal_bronze",
    iconColor: "#d97706",
    criteria: "third_overall",
    sortOrder: 20,
  },
  {
    slug: "dominator",
    name: "Dominator",
    description: "Highest number of race wins in the season",
    category: "season_heroes",
    iconName: "badge_bolt",
    iconColor: "#ef4444",
    criteria: "dominator",
    sortOrder: 21,
  },
  {
    slug: "most_improved",
    name: "Most Improved",
    description: "Biggest gain in championship position from first to last round",
    category: "season_heroes",
    iconName: "badge_trending_up",
    iconColor: "#10b981",
    criteria: "most_improved",
    sortOrder: 22,
  },
  {
    slug: "podium_king",
    name: "Podium King",
    description: "Most podium finishes in a season",
    category: "season_heroes",
    iconName: "badge_gem",
    iconColor: "#a855f7",
    criteria: "podium_king",
    sortOrder: 23,
  },
  {
    slug: "the_flash",
    name: "The Flash",
    description: "Most pole positions in a season",
    category: "season_heroes",
    iconName: "badge_zap",
    iconColor: "#fbbf24",
    criteria: "the_flash",
    sortOrder: 24,
  },
  {
    slug: "top_half_hero",
    name: "Top Half Hero",
    description: "Finish in the top 50% in 4 races",
    category: "season_heroes",
    iconName: "badge_target",
    iconColor: "#3b82f6",
    criteria: "top_half_hero",
    threshold: 4,
    sortOrder: 25,
  },

  // Legends (2 badges)
  {
    slug: "league_legend",
    name: "League Legend",
    description: "Compete in 3+ seasons AND score podiums",
    category: "legends",
    iconName: "badge_legend_star",
    iconColor: "#eab308",
    criteria: "league_legend",
    threshold: 3,
    sortOrder: 26,
  },
  {
    slug: "hall_of_fame",
    name: "Hall of Fame",
    description: "Win 2+ championships in your league career",
    category: "legends",
    iconName: "badge_hall_of_fame",
    iconColor: "#f59e0b",
    criteria: "hall_of_fame",
    threshold: 2,
    sortOrder: 27,
  },

  // League Laughs (7 badges)
  {
    slug: "plum_tomato_champion",
    name: "Plum Tomato Champion",
    description: "Finish last in 3 races",
    category: "league_laughs",
    iconName: "badge_tomato",
    iconColor: "#dc2626",
    criteria: "plum_tomato_champion",
    threshold: 3,
    sortOrder: 28,
  },
  {
    slug: "quali_merchant",
    name: "Quali Merchant",
    description: "Most times qualifying higher than finishing",
    category: "league_laughs",
    iconName: "badge_chart_down",
    iconColor: "#f97316",
    criteria: "quali_merchant",
    sortOrder: 29,
  },
  {
    slug: "the_yo_yo",
    name: "The Yo-Yo",
    description: "Biggest swing between best and worst finish",
    category: "league_laughs",
    iconName: "badge_yo_yo",
    iconColor: "#8b5cf6",
    criteria: "the_yo_yo",
    sortOrder: 30,
  },
  {
    slug: "last_but_loyal",
    name: "Last But Loyal",
    description: "Finished last overall but attended every race",
    category: "league_laughs",
    iconName: "badge_heart_loyal",
    iconColor: "#ec4899",
    criteria: "last_but_loyal",
    sortOrder: 31,
  },
  {
    slug: "relegation_fodder",
    name: "Relegation Fodder",
    description: "Get relegated to the tier below twice",
    category: "league_laughs",
    iconName: "badge_arrow_down",
    iconColor: "#ef4444",
    criteria: "relegation_fodder",
    threshold: 2,
    sortOrder: 32,
  },
  {
    slug: "most_dramatic_swing",
    name: "Most Dramatic Swing",
    description: "Biggest single-race finish improvement from worst grid spot",
    category: "league_laughs",
    iconName: "badge_drama",
    iconColor: "#eab308",
    criteria: "most_dramatic_swing",
    sortOrder: 33,
  },
  {
    slug: "league_laughs_never_quit",
    name: "Never Quit",
    description: "Participate in all races despite finishing bottom half",
    category: "league_laughs",
    iconName: "badge_persistent",
    iconColor: "#22c55e",
    criteria: "league_laughs_never_quit",
    sortOrder: 34,
  },

  // Tier Achievements (14 badges)
  {
    slug: "back_on_the_up",
    name: "Back on the Up",
    description: "Get promoted after previously being relegated",
    category: "tier_achievements",
    iconName: "TrendingUp",
    iconColor: "#22c55e",
    criteria: "back_on_the_up",
    sortOrder: 35,
  },
  {
    slug: "double_jump",
    name: "Double Jump",
    description: "Get promoted twice in consecutive shuffles",
    category: "tier_achievements",
    iconName: "ChevronsUp",
    iconColor: "#8b5cf6",
    criteria: "double_jump",
    sortOrder: 36,
  },
  {
    slug: "top_of_the_tier",
    name: "Top of the Tier",
    description: "Finish 1st in your tier's standings after a shuffle",
    category: "tier_achievements",
    iconName: "Medal",
    iconColor: "#fbbf24",
    criteria: "top_of_the_tier",
    sortOrder: 37,
  },
  {
    slug: "bounced_back",
    name: "Bounced Back",
    description: "Get promoted within one shuffle after being relegated",
    category: "tier_achievements",
    iconName: "RefreshCw",
    iconColor: "#14b8a6",
    criteria: "bounced_back",
    sortOrder: 38,
  },
  {
    slug: "relegation_survivor",
    name: "Relegation Survivor",
    description: "Avoid relegation while finishing in the relegation zone",
    category: "tier_achievements",
    iconName: "AlertTriangle",
    iconColor: "#f97316",
    criteria: "relegation_survivor",
    sortOrder: 39,
  },
  {
    slug: "s_rank_champion",
    name: "S Rank Champion",
    description: "Finish 1st overall in S Rank at the end of the season",
    category: "tier_achievements",
    iconName: "Crown",
    iconColor: "#fbbf24",
    criteria: "s_rank_champion",
    sortOrder: 40,
  },
  {
    slug: "a_rank_champion",
    name: "A Rank Champion",
    description: "Finish 1st overall in A Rank at the end of the season",
    category: "tier_achievements",
    iconName: "Award",
    iconColor: "#94a3b8",
    criteria: "a_rank_champion",
    sortOrder: 41,
  },
  {
    slug: "b_rank_champion",
    name: "B Rank Champion",
    description: "Finish 1st overall in B Rank at the end of the season",
    category: "tier_achievements",
    iconName: "Star",
    iconColor: "#d97706",
    criteria: "b_rank_champion",
    sortOrder: 42,
  },
  {
    slug: "c_rank_champion",
    name: "C Rank Champion",
    description: "Finish 1st overall in C Rank at the end of the season",
    category: "tier_achievements",
    iconName: "Circle",
    iconColor: "#78716c",
    criteria: "c_rank_champion",
    sortOrder: 43,
  },
  {
    slug: "safe_hands",
    name: "Safe Hands",
    description: "Finish outside relegation spots for an entire season",
    category: "tier_achievements",
    iconName: "Shield",
    iconColor: "#22c55e",
    criteria: "safe_hands",
    sortOrder: 44,
  },
  {
    slug: "held_the_line",
    name: "Held the Line",
    description: "Remain in the same tier after a shuffle",
    category: "tier_achievements",
    iconName: "Anchor",
    iconColor: "#3b82f6",
    criteria: "held_the_line",
    sortOrder: 45,
  },
  {
    slug: "untouchable",
    name: "Untouchable",
    description: "Avoid relegation from S Rank for a full season",
    category: "tier_achievements",
    iconName: "Sparkles",
    iconColor: "#a855f7",
    criteria: "untouchable",
    sortOrder: 46,
  },
  {
    slug: "top_tier_material",
    name: "Top Tier Material",
    description: "Get promoted to the highest tier (S Rank)",
    category: "tier_achievements",
    iconName: "Rocket",
    iconColor: "#ef4444",
    criteria: "top_tier_material",
    sortOrder: 47,
  },
  {
    slug: "elevator_operator",
    name: "Elevator Operator",
    description: "Get promoted and relegated in the same season",
    category: "tier_achievements",
    iconName: "Activity",
    iconColor: "#8b5cf6",
    criteria: "elevator_operator",
    sortOrder: 48,
  },
];
